# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_asset_asset_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_username',
            field=models.CharField(default='xebest', max_length=30),
        ),
    ]
