# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_auto_20160523_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_wireless_ip',
        ),
    ]
