# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0011_asset_asset_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_remarks',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
