# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0013_auto_20160525_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
