# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0014_auto_20160525_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_configuration',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
