# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0015_auto_20160526_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shines_notes', models.CharField(max_length=128, verbose_name='\u5907\u6ce8')),
                ('shines_neiwang_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5185\u7f51ip')),
                ('shines_waiwang_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5916\u7f51ip')),
            ],
        ),
    ]
